name: Docker Jekyll 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Pull the images
      run: |
           docker pull sylhare/jekyll
           docker pull sylhare/type-on-strap
    - name: Build the site in the jekyll/builder container
      run: docker build . -t sylhare-blog
